BUGS = [
    {
        "id": "B1",
        "title": "dotenv 不覆盖已有 OPENAI_API_KEY",
        "symptom": "探测 DeepSeek 返回 401，报错里的 key 后缀不是 .env 里那串。",
        "wrong_guess": "用户给的 Key 无效，或 DeepSeek 模型名错了。",
        "root_cause": "进程里已有另一个 OPENAI_API_KEY。load_dotenv 默认不覆盖已存在变量。",
        "fix": "load_dotenv(..., override=True)，以项目 .env 为准。",
        "next_question": "如果 CI 和本机都注入了同名变量，你以谁为准？为什么？",
    },
    {
        "id": "B2",
        "title": "deepseek-v4.1-flash 不是官方模型 id",
        "symptom": "按产品名调用会失败或被拒。",
        "wrong_guess": "SDK 版本不对。",
        "root_cause": "官方 ChatCompletions 模型名是 deepseek-flash，V4.1 Flash 走这个 id。",
        "fix": "MODEL_ALIASES 把 deepseek-v4.1-flash 映射到 deepseek-flash。",
        "next_question": "兼容别名和真实计费模型不一致时，health 接口该暴露哪一个？",
    },
    {
        "id": "B3",
        "title": "DeepSeek 默认 thinking 干扰 Tool Calling",
        "symptom": "工具调用不稳定，或先吐一段思维再调工具。",
        "wrong_guess": "prompt 没写清楚。",
        "root_cause": "V4.1 Flash 默认 thinking；Agent 循环要的是稳定 function call。",
        "fix": "extra_body.thinking.type=disabled。",
        "next_question": "什么时候应该打开 thinking？和工具循环如何分工？",
    },
    {
        "id": "B4",
        "title": "Q7 引用无关手册变成 supported",
        "symptom": "run-fail-nolog 没有日志，模型仍给出 supported。",
        "wrong_guess": "Critic 没跑。",
        "root_cause": "retrieve_runbook 命中了别的故障手册，Critic 只检查 evidence_id 是否存在。",
        "fix": "本 run 的日志/清单都不可用时，硬门槛 verdict=insufficient。",
        "next_question": "通用手册能不能单独支持一条根因？什么条件下可以？",
    },
    {
        "id": "B5",
        "title": "真 evidence_id 配假根因",
        "symptom": "引用了 OOM 日志，结论写成硬件故障，Critic 仍通过。",
        "wrong_guess": "要上第二个大模型当裁判。",
        "root_cause": "Critic 最初只校验指针，不看文本是否和 first_error 矛盾。",
        "fix": "claim 含硬件故障且证据是 CUDA OOM 时拒绝。",
        "next_question": "这种规则会不会误杀合理的「硬件相关」推断？边界怎么画？",
    },
    {
        "id": "B6",
        "title": "注入句写在用户问题里，不在日志",
        "symptom": "口述是间接注入，fixture 日志里没有那句话。",
        "wrong_guess": "模型自己会编出注入句。",
        "root_cause": "Q4 文案把注入放在 question，和手册 Q10 的「日志注入」对不上。",
        "fix": "把 IGNORE ALL RULES... 写进 run-fail-oom 的 log_excerpt。",
        "next_question": "直接注入和间接注入的控制点分别在哪一层？",
    },
    {
        "id": "B7",
        "title": "前端 innerHTML 拼接模型/日志",
        "symptom": "不可信文本进 DOM，和「日志不可执行」叙事冲突。",
        "wrong_guess": "本地 Demo 没有 XSS 风险。",
        "root_cause": "用模板字符串把 claim/log 插进 innerHTML。",
        "fix": "改为 createElement + textContent。",
        "next_question": "SSE 推过来的 JSON 还要不要再转义一次？",
    },
    {
        "id": "B8",
        "title": "同步 /analyze 堵死页面",
        "symptom": "一次分析要等完整 ReAct，HTTP 一直转圈。",
        "wrong_guess": "模型太慢，换更快的模型就行。",
        "root_cause": "分析在请求线程里跑完才返回。",
        "fix": "立即返回 job_id，线程 Worker + SSE + SQLite 轨迹。",
        "next_question": "进程崩了未完成的 job 怎么恢复？checkpoint 恢复不了什么？",
    },
]
